### ISSUE TITLE
Recent changes to the python library seem to have caused a bunch of loggers to log with insanely high verbosity

### ISSUE THREAD

**Issue by colonelpanic8** [hatchet-dev/hatchet-python#100]
This seems to happen even when hatchet is only being used for its client.

It would be nice if end users could opt out of any logging handlers (except maybe in the case of workers).

I think the general consensus of the python community is that libraries should avoid touching logging configuration.

**Comment by abelanger5** [comment]
Hey @colonelpanic8, this should be fixed in sdk version `0.31.4` (#101 and #102). Let me know if you're still seeing this!

**Comment by colonelpanic8** [comment]
Thanks. I'll take a look
